import Head from "next/head";
// import HomePage from "./component/HomePage";
import Login from "./pages/Login";
import { useContext, useEffect, useState } from "react";
import StateContext from "../store/StateContext";
import dynamic from "next/dynamic";
import { message } from "antd";

const DynamicHomepage = dynamic(() => import("./component/HomePage"), {
  ssr: false,
});

export default function Home() {
  const { loggedIn } = useContext(StateContext);

  return (
    <div>
      {message.success('This is a success message')}
      <Head>
        <title>Todo App</title>
        <meta name="descrHiption" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loggedIn ? <DynamicHomepage /> : <Login />}
    </div>
  );
}
